### ISSUE TITLE
Police alert is not working 

### ISSUE THREAD

**Issue by mrnet112** [qbcore-framework/qb-storerobbery#16]
when i start breaking cash or safe from small stores, police wont get any notification, im talking about the server original without adding any script from out of the server. and police Emergency button and ambulance not working too. in general all alerts are not working properly. please if you could take a lock and check them. Thank you

**Comment by Zael98** [comment]
think i find the solution, some commands are bad writed the help of the command, for example: the command me (default command of qb-core) QBCore.Commands.Add('me', 'Show local message', {{ name = 'id', help = 'Player ID' } }, false, function(source, args)  and i change it to: 
QBCore.Commands.Add('me', 'Show local message', {}, false, function(source, args)
after this dont happen more, is probably happen with more commands so i will change all the commands who give the problem.
for the moment for me is fixed after change 4 commands. if someone have the problem probably this will be the solution.
Try it and give me the feedback about the solution.
