### ISSUE TITLE
qb-lock Cash Register Lockpicking

### ISSUE THREAD

**Issue by Glen92** [qbcore-framework/qb-storerobbery#30]
Hey,

How do i get the lockpicking part work with qb-lock NoPixel Inspired.
When i lockpick the cash registers it still shows to original lockpicking ui.

Thanks in advance

**Comment by trclassic92** [comment]
This has already been done.. nathanERP https://github.com/NathanERP/qb-storerobbery or you can view mygithub of the forkversion to qb-storerobbery which uses qb-lock from nathanERP, The only thing different with mine is I dont use the qb-target.

**Comment by trclassic92** [comment]
https://github.com/NathanERP/qb-storerobbery This has already been done.
