### ISSUE TITLE
Stickynotes and drawtext

### ISSUE THREAD

**Issue by MrRasmus** [qbcore-framework/qb-storerobbery#35]
I have a problem with stickynotes not working and drawtext coming up already when you want to rob the register
It says the cash register is empty already while robbing it and stickynotes is not useable to get the combination code 

Hope you can fix these - I have not changed anything in the script

**Comment by FjamZoo** [comment]
Sticky note is not meant to be useable you can read its description, for the cash register being empty its because its already been robbed.
