### ISSUE TITLE
cashA, cashB [BUG]

### ISSUE THREAD

**Issue by Andyauk** [qbcore-framework/qb-storerobbery#38]
**Describe the bug**
under server/main the error  worth = math.random(cashA, cashB)
now comes up on the new update.

**To Reproduce**
1. Go to '...'a till and try to brake into it.
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**
marked money ect.

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? [e.g. yes/no]

**Additional context**

**Comment by FjamZoo** [comment]
please update your issue with additional information and screenshots
