### ISSUE TITLE
[BUG] Not receiving money from register

### ISSUE THREAD

**Issue by TehGuardian** [qbcore-framework/qb-storerobbery#40]
**Describe the bug**
Keep getting Server error in log.

SCRIPT ERROR: @qb-storerobbery/server/main.lua:40: attempt to index a nil value (field '?')

After lockpicking register don't get reward.

**Screenshots**
https://i.imgur.com/cyQiOZo.png

**Comment by Andyauk** [comment]
> **Describe the bug** Keep getting Server error in log.
> 
> SCRIPT ERROR: @qb-storerobbery/server/main.lua:40: attempt to index a nil value (field '?')
> 
> After lockpicking register don't get reward.
> 
> **Screenshots** https://i.imgur.com/cyQiOZo.png

its been like that for the past few updates. not sure why.

`    if #(playerCoords - Config.Registers[register][1].xyz) > 3.0 or (not Config.Registers[register].robbed and not isDone) or (Config.Registers[register].time <= 0 and not isDone) then
`

**Comment by BerkieBb** [comment]
This was fixed

**Comment by TheSilentGhost** [comment]
I can confirm this was not fixed
