### ISSUE TITLE
[BUG] how many police officers are sending so many alerts

### ISSUE THREAD

**Issue by shane0011** [qbcore-framework/qb-storerobbery#41]
If I start robbing a store, the store will send the notice to the police, but it will send out as many police officers on duty

What can i do to send out just ONE notification?

**Comment by nzkfc** [comment]
Also having this issue: 
![image](https://user-images.githubusercontent.com/5011997/175778037-63667018-733f-4276-9275-eda099ef29a3.png)

Pulled fresh script last week friday and also compared it to the latest and only difference is that we switched the markedmoney for small bills as an item from qb-traphouse.

**Comment by jeann2013** [comment]
Resource Sends two messages because is stealing two different things from the same store, for example, first stealing the cash register and then the vault.


1- My proposal is to be specific in the message, saying that you are stealing the cash register and when you start the theft in the vault that shows a message saying that are stealing a vault for the same store.

Or

2- If we want a single message then we would have to do like a warning counter or a flags. 


What you think @shane0011?

**Comment by kokorog** [comment]
same issue it also adds blips so that makes it unusable because police mans will not know wich one is real

**Comment by jeann2013** [comment]
@kokorog  @shane0011 OK, the solutions would be a message?

**Comment by nzkfc** [comment]
> @kokorog @shane0011 OK, the solutions would be a message?

Don't think you understand, it's not due to someone robbing a safe and a cash register.

If a single person robs a cash register, every single store that is configured will ping up as a notification and then all the blips come up for each robbery.

**Comment by jeann2013** [comment]
I actually understand that.

But I tested with the latest version of the resource and it only gives one message per cash register and one message for the vault of that store, but not at the same time, only one message for each one, that is to say if only one cash register is stolen it only sends that message for that store only.

**I believe you, I will try again**

**Comment by nzkfc** [comment]
Then that means the script is working fine.

**Comment by nzkfc** [comment]
Just went and compared qb-storerobbery and qb-policejob to see if there was any differences, theres none other then a few custom tweaks we have, like getting a different item instead of marked money etc.

So im not sure what is causing these mass pings to come up.

**Comment by jeann2013** [comment]
@nzkfc  Sorry man, but I Could not replicate issue, you can send me a video with issue, please

**Comment by nzkfc** [comment]
> @nzkfc Sorry man, but I Could not replicate issue, you can send me a video with issue, please

Hey sorry been busy fixing some stuff :) here is a video: https://youtu.be/wnr9owj8UW4?t=18

Basically if anyone robs a till or tries the safe, it pings every store as being robbed, not just that one. Plus if players spam it, the pings do it each time of course.

I'm not sure if it's our qb-storerobbery (more then happy to zip it up and share) but I did compare it to fresh and it's only minor tweaks unrelated to the pings that we changed (e.g markedbills to a rolledbill item etc)

**Comment by jeann2013** [comment]
Do you have the latest version of the resource?

**Comment by nzkfc** [comment]
Not latest as of today but I'm happy to compare it and show you the
differences.

**Comment by nzkfc** [comment]
Compare:
https://i.imgur.com/UdXPD0X.png

Differences:
config.lua: https://i.imgur.com/cQN3OeE.png

main\server.lua: https://i.imgur.com/WaVuNeb.png

**Comment by nzkfc** [comment]
> Do you have the latest version of the resource?

Compare:
https://i.imgur.com/UdXPD0X.png

Differences:
config.lua: https://i.imgur.com/cQN3OeE.png

main\server.lua: https://i.imgur.com/WaVuNeb.png

**Comment by nzkfc** [comment]
> Do you have the latest version of the resource?

Any luck? I'm happy to check/test anything you want me to, too work out what this could be.

**Comment by jeann2013** [comment]
couldn’t reproduce this issue, so weird

**Comment by nzkfc** [comment]
Wondering if this could be related to having EMS/Police blips shared with each other.

**Comment by nzkfc** [comment]
> If I start robbing a store, the store will send the notice to the police, but it will send out as many police officers on duty
> 
> What can i do to send out just ONE notification?

~~We finallllly fixed ours, was qb-phone alerting even though we use GKS Phone so it was doing a weird spam glitch~~

Ahhhh no we didn't fix it lol, we managed to fix the spam of the notifications and putting a blip/ping at each on-duty officer, but it stopped the notifications all together.

Seems like whatever is causing the notifications to spam up per cop is due to police:client:policeAlert but not sure why.

**Comment by sinphoenix** [comment]
issue still happening?

**Comment by nzkfc** [comment]
No idea, we gave up amd replaced the script with a paid one that worked and
updated dispatch

**Comment by ry304** [comment]
YesThanks, RyanSent from my iPhoneOn Apr 23, 2023, at 11:58, sinphoenix ***@***.***> wrote:﻿
issue still happening?
