### ISSUE TITLE
till opening error [BUG]

### ISSUE THREAD

**Issue by Andyauk** [qbcore-framework/qb-storerobbery#43]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Go to 'a store, and to the till, use lockpick, play the mini game, when the progress bar is over, you get a error message'
2. Click on 'not a click on, use lockpick at a till'
3. Use this item 'advancedlockpick lockpick' (item's name from shared.lua if applicable)
`[script:qb-storerobbe] SCRIPT ERROR: @qb-storerobbery/server/main.lua:40: attempt to index a nil value (field '?')`

**Expected behavior**
Go to a store, and to the till, use toolkit, play the mini game, when the progress bar is over, you get

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] up to date version
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] fresh instill and live
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Additional context**
I had this bug report open for months and it was closed, with no real reason.

**Comment by xchopin** [comment]
same bug seems like it has always been broken

**Comment by jeann2013** [comment]
@Andyauk **I need  screenshots , videos explain the issue** , I tried different stores and no achieve reproduce the bug

**Comment by MajiSP** [comment]
Having this issue as well @jeann2013 

Here is the snippet:
![image_2022-09-14_154318490](https://user-images.githubusercontent.com/30206796/190258436-59ba81a9-870b-4af7-bb0b-4159c407340a.png)
![image_2022-09-14_154326433](https://user-images.githubusercontent.com/30206796/190258456-270b9eb5-120d-4b60-adfc-ae6dded2e93d.png)

**Comment by OMikkel** [comment]
You might be missing some properties in your config file, could you please take a screenshot of your Config.Registers

**Comment by Andyauk** [comment]
> You might be missing some properties in your config file, could you please take a screenshot of your Config.Registers

<a href="https://ibb.co/4YpBj7L"><img src="https://i.ibb.co/P9gB5Ny/store.png" alt="store" border="0"></a>

**Comment by Andyauk** [comment]
i think its to do with Config.Registers[register][1].xyz) as in the confit there is no [register]

**Comment by OfficialRDB** [comment]
I tested all locations from the config. Weird part is some work without error and some don't, BUT after a restart it's other that do work and others are not. It's random all the time. I can not figure out what this issue could be.

**Comment by Andyauk** [comment]
> I tested all locations from the config. Weird part is some work without error and some don't, NUT after a restart it's other that do work and others are not. It's random all the time. I can not figure out what this issue could be.

more looking into it. when i put in a older version in. its fine. looking into that to the new one i think it could be to do with the local files, like it cant see if its on English ect. its like that with the customs too.
