### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by viransugames** [qbcore-framework/qb-storerobbery#47]
Can any One Please guide me with the safe code keypad issue, how to use or configure it

**Comment by ghost** [comment]
The safes that can be robbed are located in the config.lua under **Config.Safes**. After successfully breaking into a register there is a random number generator that is in the **server.lua**. **if math.random(1, 100) <= 10 then** this checks if 1 is lower than or equal to 10 (which can be changed in the server.lua), and if it is you will receive safe codes into your inventory. With the safe codes go to the safe in the back of the store and use those numbers to break into the safe.

**Comment by sinphoenix** [comment]
Has your issue been resolved?
