### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by FiZzontje** [qbcore-framework/qb-storerobbery#48]
No police alert when robbing you only get 1 interference per server / script restart

**Comment by OMikkel** [comment]
Could you supply some more info on that I might look into the issue, but I don't know what you are robbing and what is meant by  "1 interference per server / script restart"

**Comment by FiZzontje** [comment]
so if there is a shop robbery, the police get 1 message but if more people do this, there is no more notification until I restart the server or script or could the problem be with qb-policejob?

**Comment by OMikkel** [comment]
Have you modified `qb-policejob` or `qb-storerobbery`?
And have you updated to the last version? I will test it later today.

**Comment by FiZzontje** [comment]
yes with translation to dutch and places changed have i changed something that was not allowed? And updated all scripts after that it stop working

**Comment by OMikkel** [comment]
When did you last update? It works for me and I cloned the repo today

**Comment by FiZzontje** [comment]
I think about 1 week ago i look for the updates Thanks for youre time buddy

**Comment by sinphoenix** [comment]
i can not get this to happen. still having this issue?
