### ISSUE TITLE
[BUG] alerts

### ISSUE THREAD

**Issue by Exyztence** [qbcore-framework/qb-storerobbery#52]
When a store robbery starts, police officers get 100 alerts + 100 blips on the map (and never in the position where the robbery is). They don't know where they should go. It is the newest version of the script, I downloaded it yesterday, no modifying files
![image](https://user-images.githubusercontent.com/49649458/202912641-abac9b00-b0cb-4968-9d9f-ae9f00c5d720.png)

**Comment by Pride1922** [comment]
I tested this yesterday on a fresh qbcore installation. Everything works as expected and I could not reproduce this. 

I think this should be closed as I could not find any bug.

**Comment by Apatt7882** [comment]
I am having the same issue.

**Comment by LYRYCAL** [comment]
> When a store robbery starts, police officers get 100 alerts + 100 blips on the map (and never in the position where the robbery is). They don't know where they should go. It is the newest version of the script, I downloaded it yesterday, no modifying files ![image](https://user-images.githubusercontent.com/49649458/202912641-abac9b00-b0cb-4968-9d9f-ae9f00c5d720.png)

Did you using onesync infinity?

**Comment by sinphoenix** [comment]
what alert system are you using?
