### ISSUE TITLE
[BUG] with money

### ISSUE THREAD

**Issue by Juller12** [qbcore-framework/qb-storerobbery#56]
**Expected behavior**
A clear and concise description of what you expected to happen. Hi, when i lockpick cash register i dont get money i only get this error

**Screenshots**
![image](https://user-images.githubusercontent.com/123899537/219016736-2ea40066-3dd0-45fc-92fb-69a7458ebf68.png)

**Questions (please complete the following information):**
 - When you last updated: Im with the latest script and qb-core
 - Are you using custom resource? no
 - Have you renamed `qb-` to something custom? yes

**Comment by i-kulgu** [comment]
This is not qb-storerobbery, ask the author for support.

**Comment by i-kulgu** [comment]
There is something wrong with your register locations in your configuration.
Download a clean version and test it out again with default qb-storerobbery

**Comment by Juller12** [comment]
its not working again

**Comment by LYRYCAL** [comment]
Yeah i got this problem too, i use a clean version.

**Comment by Krisb239** [comment]
happening to me from a fresh install also

**Comment by sinphoenix** [comment]
is this issue still happening?

**Comment by CptNoHand** [comment]
This happens, when two people rob the same store, too, cause it isnt synced between players

**Comment by sinphoenix** [comment]
i can not get this to happen, but will be looking into this more today!

**Comment by 300grim** [comment]
Anyone found a solution to this yet? Also having this problem In my server.

**Comment by Hqkumaru** [comment]
I have this problem in 4 servers does anyone know how to fix it

**Comment by Juller12** [comment]
I have this problem in 3 servers does anyone know how to fix it

**Comment by 300grim** [comment]
> I have this problem in 3 servers does anyone know how to fix it 

I found a fix, contact me on discord and I can help you get this sorted out.

My discord is grim300 (no hashtag numbers)
