### ISSUE TITLE
Change minigame option for qb-storerobbery

### ISSUE THREAD

**Issue by jollyjoee** [qbcore-framework/qb-storerobbery#57]
**Is your feature request related to a problem? Please describe.**
I have ps-ui (a minigame resource) and I cant find a way to integrate it into qb-storeroberry, unlike qb-vehiclekeys (which I was able to create a script using ps-ui).

**Describe the feature you'd like**
Add some sort of TriggerEvent for the lockpick minigame (like qb-vehiclekeys/config.lua)

**Comment by megajkobe** [comment]
The lockpick mini game isn't under qb-storerobbery, the mini game is under qb-lockpicking

**Comment by jollyjoee** [comment]
> The lockpick mini game isn't under qb-storerobbery, the mini game is under qb-lockpicking

I see, is there a way to change the script used for the minigame? like, where can i insert the code for my minigame script? Like in qb-vehiclekeys, instead of using the qb-lockpicking script, i inserted a script that uses ps-ui instead only through the config file.

**Comment by megajkobe** [comment]
There isn't a config file for the lockpick script. But I would assume you could just add it to the store robbery where the lockpick script is.
