### ISSUE TITLE
No Sticky Note

### ISSUE THREAD

**Issue by frostypxrp** [qbcore-framework/qb-storerobbery#60]
After I rob the till ( I tried robbing both as well) I don't receive a stick note for the safe code? I do have the item in my city too.

**Comment by TheCoati** [comment]
There is a 10% change you will get a sticky note from the robbery you do not always get the vault code by default.

> See https://github.com/qbcore-framework/qb-storerobbery/blob/main/server/main.lua#L53C8-L53C8
