### ISSUE TITLE
required [assets]

### ISSUE THREAD

**Issue by GeekHamza1** [qbcore-framework/qb-storerobbery#7]
user need to download safecracker to complete store robbing
![Uploading screenshot_139.png…]()

**Comment by BerkieBb** [comment]
safecracker should already be a repository on the github but just not in the recipe I think

**Comment by BerkieBb** [comment]
Fixed with commit https://github.com/qbcore-framework/txAdminRecipe/commit/91d57b562665253bc8e62412d5b31a8e3a3b4944
