### ISSUE TITLE
Sticky note

### ISSUE THREAD

**Issue by bakerzone** [qbcore-framework/qb-storerobbery#8]
Does anyone know how you get the sticky note from the till to get into the safe via the keypad?

Can't seem to get it.

Thanks 
Angie

**Comment by PlzAdoptMee** [comment]
Did you figure it out. I cant seem to get one even after robbing the register

**Comment by lildiznick** [comment]
They drop only once in a while...actually once in a blue moon....lol I've done like 100 store robberies and have only had sticky notes drop twice.

**Comment by PlzAdoptMee** [comment]
Is there anything in the config to change the rate

**Comment by r44miz** [comment]
??
